GET http://localhost:3000

#TODO Get All
###
GET http://localhost:3000/suppliers

#TODO Get Detail berdasarkan id
###
GET http://localhost:3000/suppliers/1

#TODO Create data
###
POST http://localhost:3000/suppliers
Content-Type: application/json

{
  "name": "Corn Factory",
  "address": "Bandung"
}

#TODO Update data berdasarkan id
###
PUT http://localhost:3000/suppliers/4
Content-Type: application/json

{
  "name": "Corn Factory",
  "address": "Jakarta"
}

#TODO Delete data berdasarkan id
###
DELETE http://localhost:3000/suppliers/4